name: Backend 개발 환경 CI/CD

on:
  pull_request_target:
    branches:
      - dev
    types:
      - closed
    paths:
      - "backend/**"

  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true || !endsWith(github.ref, 'dev')
    runs-on: [ self-hosted ]
    steps:
      - name: 마지막 커밋 내역으로 checkout 한다
        uses: actions/checkout@v4
        with:
          ref: github.ref

      - name: EC2 환경에서 배포를 진행한다
        env:
          APPLICATION_CLIENT_PROPERTIES: ${{ secrets.APPLICATION_CLIENT_PROPERTIES }}
        run: |
          echo "=== JAR 빌드 ==="
          cd ~/2025-moitz/backend
          rm -rf src/main/resources/application-client.properties
          echo "$APPLICATION_CLIENT_PROPERTIES" > src/main/resources/application-client.properties
          ./gradlew clean build

          if [ $? -ne 0 ]; then
            echo "빌드 실패"
            exit 1
          fi

          JAR_PATH=$(ls ./build/libs/*SNAPSHOT.jar | head -n 1)
          if [ ! -f "$JAR_PATH" ]; then
            echo "JAR 파일이 없습니다: $JAR_PATH"
            exit 1
          fi

          echo "=== 실행 중인 앱 종료 ==="
          PID=$(pgrep -f "$JAR_PATH" || true)

          if [ -n "$PID" ]; then
            kill -15 $PID
            echo "→ 종료 완료 (PID: $PID)"
            sleep 5
          fi

          echo "=== 앱 실행 ==="
          mkdir -p ./logs
          RUNNER_TRACKING_ID="" && nohup java -jar "$JAR_PATH" > ./logs/error.log 2>&1 &
          sleep 3

          NEW_PID=$(pgrep -f "$JAR_PATH" || true)

          if [ -n "$NEW_PID" ]; then
            echo "앱 실행 성공 (PID: $NEW_PID)"
          else
            echo "앱 실행 실패 ./logs/error.log"
            exit 1
          fi
